### ISSUE TITLE
WOW! so nice!

### ISSUE THREAD

**Issue by PySimpleGUI** [DonnC/RabbitGUI#1]
Most people don't do the smart thing you did.... put screenshots in the readme.

For a GUI program, it's a MUST in my opinion.  I mean, you've built something that's visual so a picture is the way to go.

I should rework the date chooser window using a PySimpleGUI built-window instead of the tkinter based one that I integrated in long ago.  I've seen some people build their own calendar right into the main window itself.

Thanks for giving PySimpleGUI a shot and thanks for the Tweet!!  Congrats on making a nice looking application.

**Comment by DonnC** [comment]
sorry for the late response, Thank you for the comments and liking, it means a lot.

**Comment by PySimpleGUI** [comment]
BTW, if you upgrade to a newer PySimpleGUI, you'll get a much much nicer date chooser.

Here's the basic version with an ok/cancel button (a plain call to `popup_get_date`)

![image](https://user-images.githubusercontent.com/46163555/93000915-3d422300-f4f9-11ea-8342-625584cc286f.png)

You can also configure it to return immediately when a date is chosen, thus negating the need for OK/Cancel. 

![image](https://user-images.githubusercontent.com/46163555/93000943-606cd280-f4f9-11ea-961c-d716b955700b.png)

Finally, unlike the old date chooser, the new one uses the current theme so that it matches your window's color theme.  Here's what Dark Red looks like:

![image](https://user-images.githubusercontent.com/46163555/93000965-8b572680-f4f9-11ea-81c3-ce904fa6d3e4.png)


Or, if you're into the "Dark Themes" like people seem to be into now, these Dark Grey ones are nice too:

![image](https://user-images.githubusercontent.com/46163555/93001014-ee48bd80-f4f9-11ea-8e21-69ba35ec318f.png)

**Comment by DonnC** [comment]
Im blown away, this is a great improvement i will try to find time after my studies to update to the latest version
Thanks for the update
